name: 'london_housing_project'
version: '1.0.0'
config-version: 2

# This profile name MUST match the top-level block in your C:\Users\alast\.dbt\profiles.yml
profile: 'london_housing_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configures how models are built by default
models:
  london_housing_project:
    staging:
      +materialized: view
    marts:
      +materialized: table